const questionData = {
    "Python Programming": [
        "What are the key features of Python?", "Explain Python's Global Interpreter Lock (GIL).",
        "Difference between List and Tuple?", "How is Memory managed in Python?",
        "What are Python Decorators?", "Explain Deep Copy vs Shallow Copy.",
        "What are Generators in Python?", "How do you handle exceptions in Python?",
        "Explain the 'self' keyword in Python classes.", "What is the purpose of __init__?",
        "Difference between Range and Xrange?", "How do you use List Comprehensions?",
        "What is PEP 8?", "Explain the difference between .py and .pyc files.",
        "How do you convert a string to an integer?", "What is the 'yield' keyword used for?",
        "Explain multi-threading in Python.", "What are lambda functions?",
        "How do you use the 'with' statement?", "What is the purpose of PYTHONPATH?"
    ],
    "Java Development": [
        "What is the JVM, JRE, and JDK?", "Explain the Pillars of OOPs.",
        "Why is Java not a purely Object-Oriented language?", "What is a 'Static' keyword?",
        "Difference between Abstract Class and Interface?", "Explain Method Overloading vs Overriding.",
        "What is the 'Final' keyword used for?", "How does Garbage Collection work in Java?",
        "Explain the Exception Hierarchy.", "What is a String Pool?",
        "Difference between HashMap and HashTable.", "What are Java Annotations?",
        "Explain the 'this' and 'super' keywords.", "What is Multi-threading in Java?",
        "What is a Constructor?", "Explain the concept of Synchronization.",
        "Difference between Checked and Unchecked exceptions.", "What is the 'volatile' keyword?",
        "Explain the Wrapper classes.", "What is the purpose of the 'transient' keyword?"
    ],
    "C++ Programming": [
        "What is a Pointer in C++?", "Difference between C and C++.",
        "What are Virtual Functions?", "Explain Inline functions.",
        "What is a Friend Class?", "Explain the concept of Destructors.",
        "Difference between Stack and Heap memory.", "What is the Standard Template Library (STL)?",
        "How does Multiple Inheritance work?", "What is a Memory Leak?",
        "Explain 'this' pointer in C++.", "What is Operator Overloading?",
        "Difference between Structure and Class.", "What are templates in C++?",
        "What is a Namespace?", "Explain Access Specifiers (Public, Private, Protected).",
        "What is a Reference Variable?", "Explain Data Abstraction.",
        "What is the use of the 'Scope Resolution Operator'?", "What is a Pure Virtual Function?"
    ],
    "Data Science": [
        "What is the difference between Supervised and Unsupervised Learning?", "Explain the Central Limit Theorem.",
        "What is a Normal Distribution?", "Explain Bias-Variance Tradeoff.",
        "What is Data Normalization?", "Explain the difference between Correlation and Causation.",
        "What is an Outlier?", "How do you handle missing data?",
        "What is the purpose of A/B Testing?", "Explain P-value and Significance Level.",
        "What is Exploratory Data Analysis (EDA)?", "Explain the confusion matrix.",
        "What is the purpose of Data Wrangling?", "What is Feature Engineering?",
        "Explain Overfitting vs Underfitting.", "What is a Box Plot used for?",
        "What is Hypothesis Testing?", "Explain Time Series Analysis.",
        "What is Gradient Descent?", "What is the difference between R-squared and Adjusted R-squared?"
    ],
    "Data Analyst": [
        "Difference between Data Mining and Data Profiling.", "What is a Pivot Table in Excel?",
        "Explain SQL Joins (Inner, Left, Right, Full).", "What is Data Cleaning?",
        "How do you create a dashboard in Tableau/PowerBI?", "What is the VLOOKUP function?",
        "Explain the importance of Data Visualization.", "What is the difference between Structured and Unstructured data?",
        "What is a KPI?", "How do you validate data?",
        "Explain Descriptive vs Predictive analytics.", "What is an ETL process?",
        "How do you handle duplicate records in a dataset?", "What is a Heatmap?",
        "Explain the 'Group By' clause in SQL.", "What is a Data Warehouse?",
        "How do you interpret a Scatter Plot?", "What is the difference between Mean, Median, and Mode?",
        "Explain Data Integrity.", "What are the common tools for Data Analytics?"
    ],
    "Machine Learning": [
        "What is Linear Regression?", "Explain Logistic Regression.",
        "How do Decision Trees work?", "What is Random Forest?",
        "Explain K-Nearest Neighbors (KNN).", "What is Support Vector Machine (SVM)?",
        "What is K-Means Clustering?", "Explain Principal Component Analysis (PCA).",
        "What is Cross-Validation?", "Explain the concept of Ensemble Learning.",
        "What is a Neural Network?", "What is Backpropagation?",
        "Explain Regularization (L1 & L2).", "What is the difference between Batch and Stochastic Gradient Descent?",
        "What is a Hyperparameter?", "Explain Reinforcement Learning.",
        "What is the 'Kernel Trick' in SVM?", "How do you measure model performance?",
        "What is Naive Bayes?", "Explain the ROC Curve."
    ],
    "Artificial Intelligence (AI)": [
        "What is the Turing Test?", "Difference between Strong AI and Weak AI.",
        "What is Natural Language Processing (NLP)?", "Explain Computer Vision.",
        "What are Expert Systems?", "What is an Agent in AI?",
        "Explain Heuristic Search.", "What is the Minimax Algorithm?",
        "What is a Knowledge-Based System?", "Explain Deep Learning.",
        "What is the difference between AI, ML, and DL?", "What is a Generative Adversarial Network (GAN)?",
        "Explain the concept of Fuzzy Logic.", "What is Robot Kinematics?",
        "What is Semantic Web?", "Explain Swarm Intelligence.",
        "What is the role of an Activation Function?", "Explain Markov Decision Processes.",
        "What is AI Ethics?", "How do Large Language Models (LLMs) work?"
    ],
    "UI/UX Design": [
        "What is the difference between UI and UX?", "What are the 10 Usability Heuristics?",
        "Explain the User Centered Design (UCD) process.", "What is a User Persona?",
        "Difference between Wireframe, Mockup, and Prototype.", "What is Information Architecture?",
        "Explain the concept of Visual Hierarchy.", "What is Typography in design?",
        "What is a Design System?", "Explain the Law of Proximity.",
        "What is Accessibility (A11y) in design?", "What is a User Journey Map?",
        "Explain Color Theory.", "What is Responsive vs Adaptive Design?",
        "What is Micro-interaction?", "How do you conduct User Testing?",
        "What is a Grid System?", "Explain the Golden Ratio in design.",
        "What is White Space and why is it important?", "What is the purpose of a Mood Board?"
    ],
    "Graphics Design": [
        "Difference between Vector and Raster images.", "What is CMYK vs RGB?",
        "Explain the Principles of Design (Balance, Contrast, etc.).", "What is Kerning and Tracking?",
        "What is the purpose of a Brand Manual?", "Explain the use of Pen Tool in Illustrator.",
        "What is Layer Masking in Photoshop?", "What is Bleed and Slug in printing?",
        "Explain the Rule of Thirds.", "What is a Logo Mark vs Word Mark?",
        "What are Serif and Sans Serif fonts?", "Explain Image Resolution (DPI/PPI).",
        "What is the Gestalt Theory?", "How do you choose a Color Palette?",
        "What is Flat Design?", "Explain Opacity vs Fill.",
        "What is Gradient Mesh?", "What is the importance of File Formats (PNG, SVG, JPEG)?",
        "How do you create a Vector Trace?", "What is 3D Rendering in design?"
    ],
    "Cyber Security": [
        "What is Phishing?", "Explain SQL Injection.",
        "What is a Firewall?", "Difference between Symmetric and Asymmetric encryption.",
        "What is a VPN?", "Explain Zero Trust Architecture.",
        "What is Malware?", "What is the purpose of a Penetration Test?",
        "Explain Multi-Factor Authentication (MFA).", "What is a DDoS attack?",
        "What is Hashing?", "Explain the CIA Triad (Confidentiality, Integrity, Availability).",
        "What is a Social Engineering attack?", "What is an SSL Certificate?",
        "Difference between Vulnerability and Exploit.", "What is a Honeypot?",
        "What is Encryption at Rest vs Encryption in Transit?", "Explain the principle of Least Privilege.",
        "What is a Brute Force attack?", "What is the role of a SOC Analyst?"
    ],
    "Cloud Computing": [
        "What is SaaS, PaaS, and IaaS?", "Difference between Public and Private Cloud.",
        "What is Serverless Computing?", "Explain Virtualization.",
        "What is AWS S3?", "Explain Elasticity vs Scalability.",
        "What is a Load Balancer?", "What is a Cloud Native application?",
        "Explain Docker and Containers.", "What is Kubernetes?",
        "What is Multi-cloud Strategy?", "Explain Cloud Migration.",
        "What is Availability Zone?", "What is an API Gateway?",
        "Explain Identity and Access Management (IAM).", "What is Edge Computing?",
        "What is Cold Storage in Cloud?", "Explain Disaster Recovery in Cloud.",
        "What is Microservices Architecture?", "What is the shared responsibility model?"
    ],
    "Mobile App Development": [
        "Difference between Native and Cross-platform apps.", "What is React Native?",
        "Explain the Activity Lifecycle in Android.", "What is Swift for iOS?",
        "What is Flutter?", "Explain the concept of App Sandboxing.",
        "What is an APK and IPA file?", "Explain Push Notifications.",
        "What is Mobile UI design?", "How do you handle offline storage in apps?",
        "What is a WebView?", "Explain the role of Gradle in Android.",
        "What is the App Store optimization?", "What is Hot Reload in Flutter?",
        "Explain Deep Linking.", "How do you integrate APIs in mobile apps?",
        "What is the purpose of an Emulator?", "What is State Management?",
        "Explain the importance of App permissions.", "What is the MVVM architecture?"
    ],
    "Software Engineering": [
        "What is the SDLC (Software Development Life Cycle)?", "Explain Agile Methodology.",
        "What is Scrum?", "Difference between Waterfall and Agile.",
        "What is Version Control (Git)?", "Explain CI/CD pipeline.",
        "What is Unit Testing?", "What is Integration Testing?",
        "Explain the SOLID principles.", "What is a Design Pattern?",
        "What is Refactoring?", "Explain Technical Debt.",
        "What is the difference between QA and QC?", "What is a Requirements Specification (SRS)?",
        "Explain Code Review process.", "What is Pair Programming?",
        "What is Regression Testing?", "Explain System Architecture.",
        "What is the importance of Documentation?", "What is User Acceptance Testing (UAT)?"
    ],
    "Database Management (DBMS)": [
        "What is a Primary Key vs Foreign Key?", "Explain Normalization (1NF, 2NF, 3NF).",
        "What is ACID property in SQL?", "Difference between SQL and NoSQL.",
        "What is an Index in a database?", "Explain Stored Procedures.",
        "What is a Database Trigger?", "What is a View in SQL?",
        "Explain the concept of Deadlock.", "What is Data Redundancy?",
        "What is an Entity-Relationship (ER) Diagram?", "Explain Transaction Management.",
        "What is Database Sharding?", "What is Replication?",
        "Difference between Delete, Truncate, and Drop.", "What is a Subquery?",
        "Explain Concurrency Control.", "What is a Data Dictionary?",
        "What is Big Data?", "Explain the CAP Theorem."
    ],
    "Digital Marketing": [
        "What is SEO (Search Engine Optimization)?", "What is SEM (Search Engine Marketing)?",
        "Difference between On-page and Off-page SEO.", "What is Content Marketing?",
        "Explain PPC (Pay Per Click).", "What is Social Media Marketing?",
        "What is Email Marketing?", "Explain Affiliate Marketing.",
        "What is Google Analytics?", "What is CTR (Click Through Rate)?",
        "Explain Backlinks.", "What is Conversion Rate Optimization (CRO)?",
        "What is Influencer Marketing?", "Explain a Marketing Funnel.",
        "What is Keyword Research?", "What is Video Marketing?",
        "Explain Remarketing/Retargeting.", "What is Domain Authority?",
        "What is Local SEO?", "Explain Bounce Rate."
    ]
};
